In [10]:
#Datetime



import datetime as dt
import time as tm

currenttime=tm.time()
print(currenttime)

currentdatetime = dt.datetime.fromtimestamp(tm.time())
print(currentdatetime)

print(currentdatetime.year, currentdatetime.month,currentdatetime.day, currentdatetime.hour , currentdatetime.minute, currentdatetime.second)

delta=dt.timedelta(days=100)



differ = currentdatetime - delta
print(differ)




1606096408.5231256
2020-11-23 01:53:28.523312
2020 11 23 1 53 28
2020-08-15 01:53:28.523312


In [12]:
# Objects and map


class people():
    
    department='Computer Science'
    
    def name(self, personname):
        self.name=personname
        
    def occupation(self, designation):
        self.occupation=designation
        

people = people()
people.name('Disha')
people.occupation('developer')

print('{} works as a {}'.format(people.name, people.occupation))

Disha works as a developer


In [13]:
# List comprehension


def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == list( i*j for i in range(10) for j in range(10) )

True

In [45]:
# Numerical Python Library (NumPy)

import numpy as np
import math

a=np.array([1,2,3])
print(a.ndim)
print(a.shape)
print(a.dtype)

d=np.zeros((3,4))
e=np.ones((1,2))
print(d)
print(e)

f=np.random.rand(6)
print(f)

g=np.arange(34,104, 5)
print(g)

h=np.linspace(1,56, 23)
print(h)

i=np.array([[1,2,3],[5,2,4]])
j=np.array([[7,3,9],[8,2,1]])
k=i+j
print(k)

print(k.sum())
print(k.min())
print(k.mean())

l=np.arange(30,135,3).reshape(5,7)
print(l)


###########################################


from PIL import Image
from IPython.display import display

# im=Image.open('chris.tiff')
#display(im)
#imagedisp = np.array(im)
#print(imagedisp.shape) 

m=np.arange(0,255,1)
print(m)
n=np.full(m.shape, 255)
print(n)
o=n-m
print(o)


######################################





1
(3,)
int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]]
[0.0380471  0.99497907 0.76004035 0.37582656 0.75603623 0.29396192]
[34 39 44 49 54 59 64 69 74 79 84 89 94 99]
[ 1.   3.5  6.   8.5 11.  13.5 16.  18.5 21.  23.5 26.  28.5 31.  33.5
 36.  38.5 41.  43.5 46.  48.5 51.  53.5 56. ]
[[ 8  5 12]
 [13  4  5]]
47
4
7.833333333333333
[[ 30  33  36  39  42  45  48]
 [ 51  54  57  60  63  66  69]
 [ 72  75  78  81  84  87  90]
 [ 93  96  99 102 105 108 111]
 [114 117 120 123 126 129 132]]
(255,)
[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255